package model;
// Generated 19-mag-2018 17.12.55 by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private Integer uid;
     private Double lat;
     private Double lng;
     private String insdate;

    public Location() {
    }

    public Location(Integer uid, Double lat, Double lng, String insdate) {
       this.uid = uid;
       this.lat = lat;
       this.lng = lng;
       this.insdate = insdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLng() {
        return this.lng;
    }
    
    public void setLng(Double lng) {
        this.lng = lng;
    }
    public String getInsdate() {
        return this.insdate;
    }
    
    public void setInsdate(String insdate) {
        this.insdate = insdate;
    }




}


